import { ElementRef, Renderer, OnDestroy, OnInit, OnChanges, AfterViewChecked } from '@angular/core';
import { DragScrollOption } from './interface/drag-scroll-option';
export declare class DragScroll implements OnDestroy, OnInit, OnChanges, AfterViewChecked {
    private el;
    private renderer;
    private _scrollbarHidden;
    private _disabled;
    private _xDisabled;
    private _yDisabled;
    private _nav;
    isPressed: boolean;
    downX: number;
    downY: number;
    rect: ClientRect;
    displayType: string;
    parentNode: HTMLElement;
    wrapper: HTMLDivElement;
    scrollbarWidth: string;
    onMouseMoveHandler: any;
    onMouseDownHandler: any;
    onMouseUpHandler: any;
	onMouseLeaveHandler: any;
    mouseMoveListener: Function;
    mouseDownListener: Function;
    mouseUpListener: Function;
	mouseLeaveListener: Function;
    nextMouseUpListener: Function;
    prevMouseUpListener: Function;
    nextTouchEndListener: Function;
    prevTouchEndListener: Function;
    prevBtn: HTMLButtonElement;
    nextBtn: HTMLButtonElement;
    prevBtnDownListener: Function;
    prevTouchStartListener: Function;
    nextBtnDownListener: Function;
    nextTouchStartListener: Function;
    navBtnDiv: HTMLElement;
    navInterval: number;
    scrollbarHidden: boolean;
    disabled: boolean;
    xDisabled: boolean;
    yDisabled: boolean;
    nav: boolean;
    constructor(el: ElementRef, renderer: Renderer);
    attach({disabled, scrollbarHidden, yDisabled, xDisabled, nav}: DragScrollOption): void;
    ngOnChanges(): void;
    ngOnInit(): void;
    ngAfterViewChecked(): void;
    ngOnDestroy(): void;
    onMouseMove(e: MouseEvent): boolean;
    onMouseDown(e: MouseEvent): void;
    onMouseUp(e: MouseEvent): boolean;
    private disableScroll(axis);
    private enableScroll(axis);
    private hideScrollbar();
    private showScrollbar();
    private checkScrollbar();
    private getScrollbarWidth();
    showNavButton(): void;
    moveLeft(speed: number, stop?: boolean): void;
    moveRight(speed: number, stop?: boolean): void;
    stopNavMov(): void;
    hideNavButton(): void;
    registerNavBrowserListeners(): void;
    registerNavMobileListeners(): void;
    mobileAndTabletcheck(): boolean;
}
export declare class DragScrollModule {
}
